#!/usr/bin/env bash
set -euo pipefail
umask 077

admin_pgp_fingerprint=B3531E573A6676E8A92060B3879D4D00108D4015
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
repo_root=$(cd -- "$script_dir/.." && pwd -P)
config="$repo_root/.sops.yaml"

cat >"$config" <<EOF
# Generated by scripts/regenerate-sops.sh from secrets/**/recipient.txt.
# Do not edit manually.
keys:
  - &admin_pgp $admin_pgp_fingerprint

creation_rules:
  - path_regex: ^secrets/(guests/[^/]+/[^/]+|hosts/[^/]+)/identity\\.sops\\.json\$
    key_groups:
      - pgp:
          - *admin_pgp
EOF

shopt -s nullglob
for recipient_file in "$repo_root"/secrets/hosts/*/recipient.txt; do
  host=$(basename "$(dirname "$recipient_file")")
  read -r recipient <"$recipient_file"

  cat >>"$config" <<EOF

  - path_regex: ^secrets/hosts/$host/secrets\\.sops\\.yaml\$
    key_groups:
      - pgp:
          - *admin_pgp
        age:
          - $recipient
EOF
done

for recipient_file in "$repo_root"/secrets/guests/*/*/recipient.txt; do
  host=$(basename "$(dirname "$(dirname "$recipient_file")")")
  guest=$(basename "$(dirname "$recipient_file")")
  read -r recipient <"$recipient_file"

  cat >>"$config" <<EOF

  - path_regex: ^secrets/guests/$host/$guest/secrets\\.sops\\.yaml\$
    key_groups:
      - pgp:
          - *admin_pgp
        age:
          - $recipient
EOF
done
