name: Check

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CACHIX_CACHE_NAME: ${{ vars.CACHIX_CACHE_NAME }}
  CACHIX_PUBLIC_KEY: ${{ vars.CACHIX_PUBLIC_KEY }}

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Clean up runner
        run: ./scripts/ci/cleanup-runner.sh

      - name: Install Nix
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/ci/install-nix.sh

      - name: Check
        run: nix shell --inputs-from path:. nixpkgs#just -c just check
